### PR TITLE
one watcher

### PR DESCRIPTION
**Pull request by wagerlabs**
This patch makes the library use a single file watcher for all operations.

### CODE REVIEW

**Comment by srid** [comment]
Please do a rebase against master. 

Also the tests (`make fulltest`) are failing:

```
src/github.com/ActiveState/tail/tail.go:102: not enough arguments in call to watch.NewInotifyFileWatcher
src/github.com/ActiveState/tail/tail.go:385: undefined: watch.Cleanup
```

**Comment by wagerlabs** [comment]
@srid Should be fixed now, sorry about that! 

By the way, I'm not sure how Docker tests would work, unless that branch replaces imports of `github.com/ActiveState/tail` with `gopkg.in/ActiveState/tail.v1`. Using `gopkg.in/tail.v1` would require creating a `go-tail` Github organization.

**Comment by wagerlabs** [comment]
Also, there seems to be a Travis problem with pulling in `gopkg.in/fsnotify.v0`.

**Comment by srid** [comment]
The `Dockerfile` does a `ADD . $GOPATH/src/github.com/ActiveState/tail/` which ensures that local source files are available under the "github.com/ActiveState/tail" import, no matter which branch you are on.

I have verified that `make fulltest` succeeds on your branch. No clue about Travis — perhaps I should use this opportunity to switch to CircleCI — but I will look into understanding and doing that gopkg tagging thing (before merging this API-breaking change due to removal of `Cleanup`).

**Comment by srid** [comment]
This closes #51

**Pull request merged**
